const MSG = {
  VALIDATION_ERR: 'Validate error',
  LOGIN_SUCCESS: 'Login success',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_MUST_BE_STRING: 'Email must be string',
  EMAIL_LENGTH: 'Email maximum 160 characters and minimum 5 characters',
  EMAIL_INVALID: 'Email invalid',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_LENGTH: 'Password maximum 160 characters and minimum 5 characters',
  EMAIL_OR_PASSWORD_INCORRECT: 'Email or password incorrect',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  TOKEN_NOT_FOUND: 'Token not found',
  LOGOUT_SUCCESS: 'Logout success',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  REGISTER_SUCCESS: 'Register success',
  USER_NOT_FOUND: 'User not found',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Check email to reset password',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  FORGOT_PASSWORD_TOKEN_INVALID: 'Forgot password token invalid',
  CHANGE_PASSWORD_SUCCESS: 'Change password success',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  ACCOUNT_IS_VERIFIED: 'Account is verified',
  VERIFY_ACCOUNT_SUCCESS: 'Verify account success',
  GET_ME_SUCCESS: 'Get me success',
  REFRESH_TOKEN_SUCCESS: 'Refresh token success',
  VERIFY_USER_INVALID: 'Verify user invalid',
  UPLOAD_AVATAR_SUCCESSFULLY: 'Upload avatar success',
  IMAGE_NOT_FOUND: 'Image not found',
  OLD_PASSWORD_INCORRECT: 'Old password incorrect',
  CHANGE_PASSWORD_SUCCESSS: 'Change password success',
  UPDATE_PROFILE_SUCCESS: 'Update profile success',
  FULLNAME_MUST_BE_STRING: 'Fullname must be string',
  FULLNAME_LENGTH: 'Fullname maximum 160 characters and minimum 2 characters',
  DATE_OF_BIRTH_ISO8601: 'Date of birth ISO 8601',
  AVATAR_MUST_BE_STRING: 'Avatar must be string',
  AVATAR_LENGTH: 'Avatar maximum 255 characters and minimum 6 characters',
  ADDRESS_MUST_BE_STRING: 'Address must be string',
  PHONE_MUST_BE_STRING: 'Phone must be string',
  ADDRESS_LENGTH: 'Address maximum 160 characters and minimum 1 characters',
  PHONE_LENGTH: 'Phone maximum 10 characters and minimum 10 characters',
  VERIFY_CODE_IS_REQUIRED: 'Verify code is required',
  FORGOT_PASSWORD_CODE_IS_REQUIRED: 'Forgot password code is required',
  FORGOT_PASSWORD_CODE_INVALID: 'Forgot password code invalid',
  GENDER_INVALID: 'Gender invalid',
  GENDER_IS_REQUIRED: 'Gender is required'
} as const

export default MSG
